config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes
  resources :categories
  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :income, dependent: :destroy
  has_many :expense, dependent: :destroy
  validates :name, presence: true
  validates :date, presence: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :category
  validates :amount, presence: true, numericality: true
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
  validates :amount, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :date)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @category = Category.find_by_id(params[:category_id])
	@expense = @category.expenses.create(expense_params)
	#@expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
		format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:category_id, :amount)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @category = Category.find_by_id(params[:category_id])
	@income = @category.incomes.create(income_params)
	#@income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
		format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:category_id, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.date %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @category.date %>
</p>

<h2>Expenses</h2>
<div id="expenses">
	<%= render :partial => @category.expense.reverse %>
</div>

<%= form_for([@categories, Expense.new], remote: true) do |f| %>
	<p><%= f.label :amount, "New Expense" %><br />
		<%= f.number_field :amount %>
	</p>
	<p><%= f.submit "Add Expense" %></p>
<% end %>

<h2>Incomes</h2>
<div id="incomes">
	<%= render :partial => @category.income.reverse %>
</div>

<%= form_for([@categories, Income.new], remote: true) do |f| %>
	<p><%= f.label :amount, "New Income" %><br />
		<%= f.number_field :amount %>
	</p>
	<p><%= f.submit "Add Income" %></p>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/create.js.erb
var new_expense = $("<%= escape_javascript(render(:partial => @expense))%>").hide();
$('#expenses').prepend(new_expense);
$('#expense_<%= @expense.id %>').fadeIn('slow');
$('#new_expense')[0].reset();

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.category %></td>
        <td><%= expense.amount %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @expense.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/create.js.erb
var new_income = $("<%= escape_javascript(render(:partial => @income))%>").hide();
$('#incomes').prepend(new_income);
$('#income_<%= @income.id %>').fadeIn('slow');
$('#new_income')[0].reset();

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.category %></td>
        <td><%= income.amount %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @income.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>